services:
  linkedin-scraper:
    build:
      context: src/
      dockerfile: linkedin_scraper/Dockerfile.linkedin-scraper
    image: linkedin-scraper
    environment:
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - LINKEDIN_EMAIL=${LINKEDIN_EMAIL}
      - LINKEDIN_PASSWORD=${LINKEDIN_PASSWORD}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - PSQL_URL=${PSQL_URL}
      - PSQL_KEY=${PSQL_KEY}

  notion-poller:
    build:
      context: src/
      dockerfile: notion_poller/Dockerfile.notion-poller
    image: notion-poller
    environment:
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - PSQL_URL=${PSQL_URL}
      - PSQL_KEY=${PSQL_KEY}
