services:
  linkedin-scraper:
    build:
      context: src/
      dockerfile: linkedin_scraper/Dockerfile.linkedin-scraper
    environment:
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - LINKEDIN_EMAIL=${LINKEDIN_EMAIL}
      - LINKEDIN_PASSWORD=${LINKEDIN_PASSWORD}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ./src/linkedin_scraper/config:/app/src/linkedin_scraper/config
    profiles:
      - scraper

  notion-poller:
    build:
      context: src/
      dockerfile: notion_poller/Dockerfile.notion-poller
    environment:
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ./src/notion_poller:/app/src/notion_poller
    profiles:
      - poller 