apiVersion: batch/v1
kind: CronJob
metadata:
  name: linkedin-scraper-cronjob
spec:
  schedule: "0 * * * *" # every hour
  jobTemplate:
    metadata:
      name: linkedin-scraper-cronjob
    spec:
      template:
        spec:
          containers:
            - name: linkedin-scraper-cronjob
              image: linkedin-scraper
              volumeMounts:
                - name: linkedin-scraper-storage
                  mountPath: /flags
          restartPolicy: Never
          volumes:
            - name: linkedin-scraper-storage
              persistentVolumeClaim:
                claimName: linkedin-scraper-pvc
