apiVersion: batch/v1
kind: CronJob
metadata:
  name: linkedin-scraper-cronjob
spec:
  schedule: "*/5 * * * *" # every hour
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      name: linkedin-scraper-cronjob
    spec:
      template:
        spec:
          containers:
            - name: linkedin-scraper-cronjob
              image: linkedin-scraper:latest
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: linkedin-scraper-storage
                  mountPath: /flags
          restartPolicy: Never
          volumes:
            - name: linkedin-scraper-storage
              persistentVolumeClaim:
                claimName: linkedin-scraper-pvc
