FROM python:3.11-slim

WORKDIR /app

# Copy source code
COPY common ./src/common
COPY notion_poller ./src/notion_poller

# Copy requirements and install Python dependencies
COPY notion_poller/pyproject.toml .
RUN pip install --no-cache-dir -e .

# Set environment variables
ENV PYTHONPATH=/app/src

# Run the notion poller
CMD ["bash", "src/common/run-if-not-recent.sh", "src/notion_poller/poller.py", "poller"]