apiVersion: batch/v1
kind: CronJob
metadata:
  name: notion-poller-cronjob
spec:
  schedule: "*/5 * * * *" # every hour
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      name: notion-poller-cronjob
    spec:
      template:
        spec:
          containers:
            - name: notion-poller-cronjob
              image: notion-poller:latest
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - name: notion-poller-storage
                  mountPath: /flags
              env:
                - name: NOTION_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: secrets
                      key: NOTION_API_KEY
                - name: NOTION_DATABASE_ID
                  valueFrom:
                    secretKeyRef:
                      name: secrets
                      key: NOTION_DATABASE_ID
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: secrets
                      key: GITHUB_TOKEN
          restartPolicy: Never
          volumes:
            - name: notion-poller-storage
              persistentVolumeClaim:
                claimName: notion-poller-pvc
