apiVersion: batch/v1
kind: CronJob
metadata:
  name: notion-poller-cronjob
spec:
  schedule: "0 * * * *" # every hour
  jobTemplate:
    metadata:
      name: notion-poller-cronjob
    spec:
      template:
        spec:
          containers:
            - name: notion-poller-cronjob
              image: notion-poller
              volumeMounts:
                - name: notion-poller-storage
                  mountPath: /flags
          restartPolicy: Never
          volumes:
            - name: notion-poller-storage
              persistentVolumeClaim:
                claimName: notion-poller-pvc
